### ISSUE TITLE
Feature request: Combine \runExtCode and \includeOutput

### ISSUE THREAD

**Issue by kiryph** [Ossifragus/runcode#8]
When one wants to include always the output of external code, the second line in following LaTeX snippet is more verbose than necessary:
```tex
\runExtCode{gap -b --nointeract}{charactertable.gap}{charactertable}[cache]
\includeOutput{charactertable}[tex]
```

The commands `\runExtCode{Arg1}{Arg2}{Arg3}[Arg4]` and `\includeOutput{Arg1}[Arg2]` could be combined to a single command, e .g.
```tex
\runExtCodeAndIncludeOutput{Arg1}{Arg2}[Arg3][Arg4]
```
with

- `Arg1` is the executable program or programming language. 
- `Arg2` is the source file
- `Arg3` optional output filename
- `Arg4` combines all options for `\runExtCode` and `\includeOutput`, i.e.
  - `run` or `cache` (if omitted, use global value)
  - `vbox`, `tex` or `inline` 

IMHO a shorter command name would be better, e.g. `\includeOutputOfExtCode`: 24 characters compared to 28 characters of `\runExtCodeAndIncludeOutput`. Reducing `include` to `inc` and `output` to `out` would give`\incOutOfExtCode` (17 characters). This is certainly up to debate and the author(s) of `runcode` should certainly choose the one which they feel makes the most sense.

My example from above would be

```tex
\incOutOfExtCode{gap -b --nointeract}{charactertable.gap}[charactertable][cache]
```

or without specifying the intermediate output file
```tex
\incOutOfExtCode{gap -b --nointeract}{charactertable.gap}[cache]
```

**Comment by Ossifragus** [comment]
Great idea! We implemented in this here: https://github.com/Ossifragus/runcode/pull/13

The details of the command are [here](https://github.com/Ossifragus/runcode#extended-commands).

We chose the command name `\runCodeIncOut` because we want it to be closer to
the package name. I agree that a shorter command name is better and changed the
command name from `\runCodeIncOutput` to `\runCodeIncOut` while I was writing
this :).

We use `Arg3` as the first optional argument to control if the code should run
or not, and use `Arg4` to take optional output file names, because the output
file name may become less important in the combined command and `run`
v.s. `cache` switch may be used more frequently. We did not combine any of
`Arg3` - `Arg5` to make the command more flexible.

Examples of usage
- No optional arguments specified:
``` tex
\runCodeIncOut{gap -b --nointeract}{charactertable.gap}
```
- use cache; not specifying output file name; include output inline
``` tex
\runCodeIncOut{gap -b --nointeract}{charactertable.gap}[cache][][inline]
```
